### ISSUE TITLE
Bonus Approaches

### ISSUE THREAD

**Issue by ydai94** [xingdi-eric-yuan/TextWorld-Coin-Collector#11]
May I ask how to modify the config file to switch between **cumulated counting bonus** and **episodic discovery bonus**? Thanks a lot

**Comment by xingdi-eric-yuan** [comment]
Hi @EthanDY , it seems we didn't include the baseline counting method into this repo (mostly because it didn't work). I will add it soon. In case you want to try it sooner, the only thing one needs to modify is [HERE](https://github.com/xingdi-eric-yuan/TextWorld-Coin-Collector/blob/master/lstm_dqn_baseline/agent.py#L339-L354), where:

1. at the beginning of each episode, the memory is not reset;
2. all batches share the same memory;
3. rewards are computed as described in the paper (page 2, left, last line).

**Comment by ydai94** [comment]
Thanks for your work!

**Comment by xingdi-eric-yuan** [comment]
Hi @EthanDY , please try the new branch [`cumulative_bonus`](https://github.com/xingdi-eric-yuan/TextWorld-Coin-Collector/tree/cumulative_bonus), in which, one can modify [THIS](https://github.com/xingdi-eric-yuan/TextWorld-Coin-Collector/blob/cumulative_bonus/lstm_dqn_baseline/config/config.yaml#L30) to switch between the counting bonus methods, or to disable it. I didn't run thorough test, so please let me know if you encounter any issues.

**Comment by EthanDY** [comment]
`<ipython-input-10-a8c569cb9d00> in train(config)
    116         elif revisit_counting == "cumulative":
    117             # do not reset counter here
--> 118             revisit_counting_rewards = agent.get_cumulative_count(new_observation_strings)
    119         else:
    120             # revisit_counting is None

/content/TextWorld-Coin-Collector/lstm_dqn_baseline/agent.py in get_cumulative_count(self, observation_strings, update)
    362         for i in range(batch_size):
    363             concat_string = observation_strings[i]
--> 364             if concat_string not in self.binarized_counter_dict[i]:
    365                 self.binarized_counter_dict[i][concat_string] = 0.0
    366             if update:

AttributeError: 'RLAgent' object has no attribute 'binarized_counter_dict'`

**Comment by EthanDY** [comment]
![image](https://user-images.githubusercontent.com/21295781/128481175-5800dc4c-4f19-4cdc-8e5d-6815c82a2777.png)

**Comment by ydai94** [comment]
![image](https://user-images.githubusercontent.com/21295781/128481203-e5db17ed-2067-481e-b12e-086d572758c4.png)
Hello @xingdi-eric-yuan , I encountered such an error. I believe this is because of the code here in the agent file:
![image](https://user-images.githubusercontent.com/21295781/128481542-d7340d6f-256e-4e4d-a515-bb9a0eee05e2.png)

**Comment by xingdi-eric-yuan** [comment]
Yes you're right, sorry for that. The new commit should fix that.

**Comment by ydai94** [comment]
It works now, thx!
