### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by lyon424** [xingdi-eric-yuan/TextWorld-Coin-Collector#12]
I was having an issue with installing pip install https://github.com/microsoft/TextWorld/archive/refs/heads/coin_collector.zip
It errors after using the command, then with the next command  I also get an error pip install gym_textworld/

**Comment by lyon424** [comment]
Then when trying to install pip install gym_textworld/
I got the error:
ERROR: Invalid requirement: 'gym_textworld/'
Hint: It looks like a path. File 'gym_textworld/' does not exist.

**Comment by MarcCote** [comment]
I'd suggest try to install it in a new conda environment using python=3.7
