### ISSUE TITLE
Version issue

### ISSUE THREAD

**Issue by lxs3213196** [xingdi-eric-yuan/TextWorld-Coin-Collector#7]
I am a beginning learner  in DRL. When I run this project on linux, there are many problems due to the incorrect version of the installation packages.I use python=3.6.13,Textworld=1.0.0,pytorch=0.4,tensorboardX=1.4,nltk=3.5,numpy=1.19.5,tqdm=4.60 But I feel that there are some versions I must have installed incorrectly..... May I ask you to provide with the versions of all the key installation packages you use?Thank you very much~

**Comment by lxs3213196** [comment]
![image](https://user-images.githubusercontent.com/71811827/113692515-30d52000-9700-11eb-9a12-2f881bbcefb7.png)
I also have this problem :AttributeError: 'str' object has no attribute 'kb' when I run python lstm_dqn_baseline/train_single_generate_agent.py -c lstm_dqn_baseline/config/, what should I do to deal with it?

**Comment by MarcCote** [comment]
Can you confirm that you have install the `coin-collector` branch from TextWorld?
`pip install https://github.com/microsoft/TextWorld/archive/refs/heads/coin_collector.zip`

**Comment by MarcCote** [comment]
Hi @lxs3213196 I've fixed the installation procedure in Readme.md (see #8). Let us know if that works for you.

**Comment by lxs3213196** [comment]
thank you very much!
